export const STAGES = Object.freeze([
  "VERIFY_RUNTIME",
  "T4_TARGETED_REGRESSION",
  "TOPIC161_ORIGINAL_DEVELOPMENT",
  "LIVE50_FULL_REGRESSION",
  "RELIABILITY_GATE",
  "VISIBLE_CRITICAL4",
  "VISIBLE_FULL69",
  "VISIBLE_TOPIC161_REPLACEMENT_V2",
  "VISIBLE_FROZEN13",
  "CANDIDATE_FREEZE",
]);

export const TERMINAL_STATES = Object.freeze([
  "READY_FOR_SEALED_UNSEEN_OWNER_AUTHORISATION",
  "BLOCKED_NOT_QUALIFIED",
]);

export const FAILURE_CLASSES = Object.freeze([
  "INFRASTRUCTURE_TEMPORARY",
  "MODEL_INVALID_OUTPUT",
  "EVALUATOR_DEFECT",
  "FROZEN_QUALIFICATION_INPUT_DEFECT",
  "GOLD_DEFECT",
  "CANONICAL_FACT_DEFECT",
  "ROUTER_SCOPE_ERROR",
  "REQUIRED_LOOKUP_MISSING",
  "REQUIRED_SOURCE_MISSING",
  "REQUIRED_SOURCE_DROPPED",
  "WRONG_SOURCE_PRIORITY",
  "WRONG_JURISDICTION",
  "VALIDATOR_FALSE_REJECTION",
  "CITATION_FORMAT_DEFECT",
  "CITATION_ENTAILMENT_DEFECT",
  "DETERMINISTIC_RECAP_DEFECT",
  "SAFETY_TEMPLATE_DEFECT",
  "MODEL_RULE_SELECTION_FAILURE",
  "MODEL_CONDITION_OR_EXCEPTION_FAILURE",
  "MODEL_FACT_APPLICATION_FAILURE",
  "MODEL_UNSUPPORTED_OUTCOME",
  "MODEL_FAIL_CLOSED_CALIBRATION_FAILURE",
  "MODEL_MULTI_ISSUE_SYNTHESIS_FAILURE",
  "AI_REVIEW_UNAVAILABLE",
  "CANDIDATE_IDENTITY_MISMATCH",
  "SOURCE_IDENTITY_MISMATCH",
  "PROTECTED_DATA_BOUNDARY",
]);

export const VISIBLE_STAGES = new Set([
  "VISIBLE_CRITICAL4",
  "VISIBLE_FULL69",
  "VISIBLE_TOPIC161_REPLACEMENT_V2",
  "VISIBLE_FROZEN13",
]);

export function nextStage(stage) {
  const index = STAGES.indexOf(stage);
  return index >= 0 ? STAGES[index + 1] || null : null;
}
