import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {runChat} from '../server/services/chatService.js';
import {processQuery} from '../server/services/queryProcessorService.js';
import {lookupStructuredData} from '../server/services/structuredDataService.js';
import {deterministicDashboardAnswer} from '../server/services/deterministicAnswerService.js';
import {renderCitationMarkers,attachCitationMarkers} from '../server/services/citationRendererService.js';
import {validateGroundedAnswer} from '../server/services/groundingService.js';
import {buildCanonicalFacts} from '../server/services/canonicalFactService.js';
import {readFileSync} from 'node:fs';
const questions=JSON.parse(readFileSync(new URL('./fixtures/live-repair/owner-questions.json',import.meta.url))).questions;
function answer(i,userId='alex-morgan') {const {sources}=lookupStructuredData(userId,{structured_lookups:['account','projection','document_status']});const d=deterministicDashboardAnswer(questions[i],{userId,sources});const r=renderCitationMarkers({answer:d.explicitClaimCitations?d.answer:attachCitationMarkers(d.answer,d.citationIds),citationIds:d.citationIds,sources:d.sources});return {d,r,v:validateGroundedAnswer({answer:r.answer,citationIds:r.citationIds,sources:d.sources,intent:'HYBRID',legalEvidenceRequired:false,claimLevel:true,claimCitations:r.claimCitations})};}
test('DEVELOPMENT_ONLY Q1 and paraphrases require official authority',()=>{for(const message of [questions[0],'Can the company alter our pension benefits?','My employer is changing contributions to the scheme','Does the company need my approval to lower future pension payments?','What happens to benefits I have already earned if the pension is amended?','Our bosses are cutting what goes into retirement funds. Is that allowed?']){const q=processQuery(message,{profileJurisdiction:'England and Wales'});assert.equal(q.legal_evidence_required,true);assert.ok(q.source_scopes.includes('CURATED_PUBLIC'));}});
test('DEVELOPMENT_ONLY Q3 retains every canonical scenario and binds rates to accounts',()=>{const {d,r,v}=answer(2);assert.equal(v.valid,true,JSON.stringify(v));const facts=buildCanonicalFacts('alex-morgan');for(const item of facts.dashboard.contributionScenarios){assert.ok(d.answer.includes(item.extraMonthlyContribution));assert.ok(d.answer.includes(item.projectedMonthlyIncome));assert.ok(d.answer.includes(item.monthlyGap));}for(const claim of r.claimCitations.filter(c=>/recorded employee contribution/.test(c.claim))) assert.ok(claim.source_ids.every(id=>id.startsWith('structured_accounts')));});
test('DEVELOPMENT_ONLY Q4 describes the recorded detail and missing locators',()=>{const {d,v}=answer(3);assert.equal(v.valid,true,JSON.stringify(v));assert.match(d.answer,/Field-level pending items and page\/section locators are not recorded/);assert.match(d.answer,/compare each extracted value/);});
test('DEVELOPMENT_ONLY Q2 is immediate without model or retrieval calls',async()=>{const previous=global.fetch;global.fetch=async()=>{throw Error('unexpected dependency request')};try{const events=[];const result=await runChat({userId:'alex-morgan',clientRequestId:randomUUID(),message:questions[1],onEvent:(event,payload)=>events.push({event,...payload})});assert.equal(result.confidence,'general_safety_notice');assert.match(result.response,/FCA Firm Checker/);assert.equal(events.some(e=>e.status==='generating'||e.status==='retrieving'),false);assert.ok(events.every(e=>e.request_id));}finally{global.fetch=previous;}});
test('DEVELOPMENT_ONLY concurrent same logical request cannot execute twice',async()=>{const id=randomUUID();const options={userId:'alex-morgan',clientRequestId:id,message:questions[3]};const first=runChat(options);await assert.rejects(runChat(options),e=>e.code==='REQUEST_IN_PROGRESS');const result=await first;const replay=await runChat(options);assert.equal(replay.message_id,result.message_id);assert.equal(replay.idempotent,true);});
test('DEVELOPMENT_ONLY pre-cancelled request does not persist or invoke dependencies',async()=>{const c=new AbortController();c.abort();await assert.rejects(runChat({userId:'alex-morgan',clientRequestId:randomUUID(),message:questions[0],abortSignal:c.signal}));});
test('DEVELOPMENT_ONLY unknown account never receives sample pension facts',()=>{const userId='new-owner-'+randomUUID();const {d,v}=answer(2,userId);assert.doesNotMatch(d.answer.replace(/\{\{cite:[^}]+\}\}/g,""),/Aviva|Nest|OneLife|Northbridge|1,696|45|67/);assert.match(d.answer,/No pension accounts are recorded/);assert.equal(v.valid,true,JSON.stringify(v));assert.equal(buildCanonicalFacts(userId).dashboard.pensionAccounts.length,0);});
test('DEVELOPMENT_ONLY transfer pressure paraphrases and contextual negatives',async()=>{const {urgentTransferPressure}=await import('../server/services/queryProcessorService.js');for(const q of ['I am being rushed to transfer my pension','They say I must transfer my pension before tomorrow','Someone is pressuring me to transfer my pension urgently.'])assert.equal(urgentTransferPressure(q),true,q);for(const q of ['I am not being pressured to transfer my pension','What is the statutory pension transfer deadline?','Can pension contributions relieve pressure on my budget?'])assert.equal(urgentTransferPressure(q),false,q);});
test('DEVELOPMENT_ONLY punctuation follow-up is a persisted clarification without generation',async()=>{const original=global.fetch;global.fetch=async()=>{throw Error('unexpected generation')};try{const result=await runChat({userId:'alex-morgan',clientRequestId:randomUUID(),message:'??'});assert.equal(result.confidence,'needs_clarification');assert.match(result.response,/clarify/)}finally{global.fetch=original}});
test('DEVELOPMENT_ONLY accepted cancellation persists and replays as cancelled without generation',async()=>{
 const {getConversation}=await import('../server/repositories/conversationRepository.js');
 const controller=new AbortController(),requestId=randomUUID();let sessionId;
 const original=global.fetch;global.fetch=async()=>{throw Error('Cancelled request reached dependency')};
 try{
  await assert.rejects(runChat({userId:'alex-morgan',clientRequestId:requestId,message:questions[0],abortSignal:controller.signal,onEvent:(event,payload)=>{if(event==='chat.accepted'){sessionId=payload.session_id;controller.abort();}}}));
  let conversation;
  for(let i=0;i<20;i++){conversation=await getConversation('alex-morgan',sessionId);if(conversation.messages.some(x=>x.metadata?.terminalState==='cancelled'))break;await new Promise(resolve=>setTimeout(resolve,10));}
  const terminal=conversation.messages.filter(x=>x.role==='assistant');assert.equal(terminal.length,1);assert.equal(terminal[0].metadata.confidence,'cancelled');
  const replay=await runChat({userId:'alex-morgan',clientRequestId:requestId,message:questions[0]});assert.equal(replay.idempotent,true);assert.equal(replay.confidence,'cancelled');
 }finally{global.fetch=original;}
});
