// New behavior examples only. Never imports evaluation banks or historical targets.
import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {ANSWER_SYSTEM_POLICY} from '../server/prompts/answerPolicy.js';
import {buildModelContext} from '../server/services/modelContextService.js';
import {structuralChunk} from '../server/services/chunkingService.js';
import {auditTrainingRows,auditTrainingPartitionIsolation} from './lib/trainingEvidenceIntegrity.mjs';
const root=resolve(process.argv[2]||'');
if(!process.argv[2]||existsSync(root))throw Error('Fresh explicit private dataset directory required');
mkdirSync(root,{recursive:true,mode:0o700});
const hash=x=>createHash('sha256').update(x).digest('hex');
const manifestPath='approved-materials/approved-corpus-manifest-20260908-repair-v1.json';
const manifest=JSON.parse(readFileSync(manifestPath));
function official(id,section){const d=manifest.documents.find(x=>x.id===id);const bytes=readFileSync(resolve('approved-materials',d.text_path));if(hash(bytes)!==d.text_sha256)throw Error('Source hash mismatch');const c=structuralChunk(bytes.toString(),{documentType:d.document_type}).find(x=>section(x.sectionPath));return {sourceId:id,documentId:id,title:d.title,section:c.sectionPath,snippet:c.content,scope:'CURATED_PUBLIC',sourceType:d.source_type,jurisdiction:d.jurisdiction,effectiveDate:d.effective_date,canonicalLocation:d.canonical_location,sourceMetadata:{scopeNote:d.scope_note,dateBasis:d.effective_date_basis,retrievedAt:d.retrieved_at,unappliedEffects:d.unapplied_effects}};}
const law=official('live-repair-pa1995-s67-20260908',s=>/Section 67\b/.test(s));
const consultation=official('live-repair-gb-consultation-20260908',s=>/Regulation 6\b/.test(s));
const guide=official('live-repair-tpr-scheme-changes-20260908',()=>true);
const items=[];
function add(partition,construct,source,question,answer){
 const item_id=`adapt-${partition}-${String(items.filter(x=>x.partition===partition).length+1).padStart(3,'0')}`;
 const query={self_contained_query:question,jurisdiction_scope:source.jurisdiction||'not recorded',response_route:'ANSWER',handoff_reason:null,response_requirements:['Give the supported explanation with its conditions. Identify facts missing for individual application; ask a narrow question when needed. Do not treat fictional records as law.']};
 const context=buildModelContext(query,[source],{snippetChars:4000});
 const citation_ids=[...new Set([...answer.matchAll(/\{\{cite:([^}]+)\}\}/g)].map(x=>x[1]))];
 const completion={answer,citation_ids};
 const row={messages:[{role:'system',content:`/no_think\n${ANSWER_SYSTEM_POLICY}`},...context.messages,{role:'assistant',content:JSON.stringify(completion)}],metadata:{training_id:item_id,construct_id:construct,partition,classification:'DEVELOPMENT_ONLY',synthetic_personal_data:true,formal_credit:false}};
 items.push({item_id,partition,construct_id:construct,question,citation_aliases:context.citationAliases,model_citation_token:'{{cite:S1}}',source:{...source,source_id:source.sourceId,text:context.evidenceSources[0].snippet,authority_family:source.documentId,content_sha256:hash(context.evidenceSources[0].snippet)},proposed_completion:completion,row_sha256:hash(JSON.stringify(row)),row});
}
const publicCases=[
 [law,'subsisting-rights',[
 ['A GB occupational arrangement has a modification power. Does the supplied section make every alteration void?','No. For occupational schemes within this section, prohibited modifications are void, while regulated modifications are voidable unless the specified requirements are met; exclusions also apply. {{cite:S1}} Which kind of modification is proposed, and is the arrangement within the section? The scheme rules and classification need review before an individual conclusion.'],
 ['A regulated modification is not protected and the scheme is not collective money purchase. Explain the alternatives shown in this extract.','For an occupational scheme within section 67, this category requires either member consent or actuarial equivalence, together with trustee approval and reporting requirements. {{cite:S1}} The extract does not establish whether those requirements have actually been met; the relevant records need checking.'],
 ['The supplied text covers protected modifications in an occupational scheme. Someone says actuarial equivalence always replaces consent. Is that reading supported?','No. Within this occupational scheme regime, a protected modification requires consent; the consent-or-actuarial-equivalence alternative applies where the specified consent-only category does not apply. Trustee approval and reporting requirements also apply to regulated modifications. {{cite:S1}} The proposed modification must be classified before using either route.'],
 ['We have only a personal pension agreement. Does the supplied occupational subsisting-rights section decide whether our contract may be rewritten?','This section concerns modification powers conferred by occupational pension schemes, with stated exclusions; it does not establish a rule for your personal pension contract. {{cite:S1}} What wording is being changed, and what does the agreement say about changes? The applicable contract and authority are needed for that conclusion.']
 ]],
 [consultation,'consultation-conditions',[
 ['A notice says a GB workplace pension proposal is a listed change. Does this extract say consultation automatically makes the proposal lawful?','The extract makes required consultation a condition before a covered person decides on a listed change; it also defines scope through further regulations and exceptions. It does not itself establish a general permission to change scheme terms. {{cite:S1}} Which proposal and scheme type are involved, and are any exclusions relevant?'],
 ['A personal pension proposal reduces company contributions, but no information about the employer or exceptions is provided. Explain what this consultation provision establishes.','Required consultation precedes a covered listed-change decision. For personal pensions, an exception covers a reduction proposed as a result of earlier consultation on ceasing employer contributions. {{cite:S1}} Are the employer and proposal covered, and did that earlier consultation occur? This extract alone does not establish member consent or a contractual amendment power.'],
 ['A colleague reads regulation 6 as saying every pension adjustment needs member consultation. Is that an accurate summary of the supplied passage?','No. It applies to covered persons making listed changes, as defined by scheme type, subject to exclusions and four stated exceptions; it is not a rule for every adjustment. {{cite:S1}} What adjustment is planned, and is the pension occupational or personal?'],
 ['An occupational scheme consulted on stopping future accrual. It now proposes reducing the accrual rate as a result of that consultation. What exception is described here?','The extract describes an exception where consultation already occurred on preventing future accrual and a resulting further proposal reduces that accrual rate. {{cite:S1}} Whether the actual sequence meets those conditions needs the consultation records and proposal wording; this is not a general exemption for all later changes.']
 ]],
 [guide,'ae-dc-guidance',[
 ['An employer is checking whether a DC arrangement qualifies for automatic enrolment. The current definition of pensionable pay fails the checks described. What kinds of changes does this guidance discuss?','In that DC automatic-enrolment context, the guidance discusses increasing employer or jobholder contributions, changing pensionable pay definitions, or changing rules to meet certification criteria. Amendments and their process should be discussed with the trustees, manager or provider. {{cite:S1}} It does not establish a universal power to alter every pension promise.'],
 ['Our planned automatic-enrolment DC amendment increases member contributions. Does this guide prove consultation always applies?','The guidance says consultation may be required for increases in member contributions and gives a 60-day period if consultation is required. {{cite:S1}} Which scheme and proposed amendment are involved? The applicable consultation rules and amendment process still need checking; the conditional guidance is not proof that every increase follows the same route.'],
 ['A proposed automatic-enrolment DC change is said to meet the contribution minimum. Does this extract prove the whole arrangement is a qualifying scheme?','No. The guidance says the effect of the changes must fulfil the relevant minimum or alternative requirements and the arrangement must also meet the other qualifying requirements. {{cite:S1}} What other qualifying checks have been completed? The contribution change alone does not settle the conclusion.'],
 ['Someone uses this DC automatic-enrolment guidance to say all benefits already earned in any pension can be reduced. Does the excerpt support that?','No. This passage discusses changes to meet DC automatic-enrolment requirements, including contributions and pensionable pay; it does not establish a general rule permitting reductions to benefits already earned. {{cite:S1}} What scheme type and past or future benefits are involved? The relevant scheme documents and legal authority are needed.']
 ]]
];
for(const [source,construct,cases] of publicCases)for(const [q,a]of cases)add('train',construct,source,q,a);
function fictional(partition,construct,text,cases){const source={sourceId:`fiction-${construct}`,documentId:`fiction-${construct}`,title:`Fictional exercise: ${construct}`,section:'Recorded exercise rules',snippet:`FICTIONAL EXERCISE ONLY. These are invented scheme records, not legislation or actual user data. ${text}`,scope:'USER_DOCUMENTS',sourceType:'SYNTHETIC_RECORD',jurisdiction:'Fictional exercise; no legal jurisdiction asserted',effectiveDate:null,sourceMetadata:{scopeNote:'Only the named fictional exercise; cannot establish UK law',dateBasis:'No real legal effective date'}};for(const[q,a]of cases)add(partition,construct,source,`In this fictional exercise, ${q}`,a);}
fictional('train','matching-tier','The Cedar example matches additional employee payments only for permanent employees after probation. Temporary employees receive no additional match. The employee status and probation end are not recorded.',[
 ['is an extra payment certain to receive matching money?','No. In the Cedar exercise, additional matching depends on permanent status and completed probation; temporary staff receive no additional match. {{cite:S1}} Are you permanent, and has probation ended? Without those facts the exercise does not establish a match.'],
 ['what is missing before you can apply the matching rule to me?','The Cedar rule makes extra matching conditional on permanent employment and completed probation, and excludes temporary staff. {{cite:S1}} Please confirm your employment status and probation end. These invented terms describe this exercise only.']]);
fictional('train','salary-basis','The Marigold example calculates contributions using basic salary, excluding overtime and bonuses. The record provides total pay only and does not break it into components.',[
 ['can the total pay figure be used directly to calculate contributions?','No. The Marigold exercise uses basic salary and excludes overtime and bonuses, while the record supplies only total pay. {{cite:S1}} What is the basic-salary component? A reliable contribution calculation needs that breakdown.'],
 ['does a large bonus automatically raise the contribution base under these terms?','No. Bonuses and overtime are excluded from the contribution base in the Marigold exercise. {{cite:S1}} The basic-salary amount is needed to calculate contributions; total pay alone is insufficient.']]);
fictional('train','retired-or-active','The Rowan example permits active members to request a contribution pause after written notice. This permission does not apply to retired members. Membership status and any notice are absent.',[
 ['may I use the recorded pause option now?','The Rowan exercise allows active members to request a pause after written notice and excludes retired members from that option. {{cite:S1}} Are you an active member, and have you given the notice? The missing facts prevent an individual conclusion.'],
 ['does this permission extend to all members?','No. In the Rowan exercise, the pause option is limited to active members after written notice; it does not apply to retired members. {{cite:S1}} Which membership category is involved?']]);
fictional('train','conflicting-fees','Two unverified Elm extracts describe an annual fee: one says 0.4%, the other 0.7%. Neither has a version date or an applicable-account identifier.',[
 ['which annual fee is correct for the account?','The Elm extracts conflict: one records 0.4% and the other 0.7%, with no version dates or account binding. {{cite:S1}} I cannot select the applicable fee from that evidence. Can you provide a dated statement for the account?'],
 ['may I use the lower figure for a forecast?','The Elm evidence contains conflicting annual fees of 0.4% and 0.7% without dates or account identifiers. {{cite:S1}} The lower figure is not established as correct. A dated, account-specific fee record is needed before using it as a confirmed forecast input.']]);
fictional('train','missing-not-zero','The Hazel record has no current pension value: the value field is null. It records a monthly contribution of zero explicitly. Neither field is a live provider update.',[
 ['is the pension worth zero with no monthly payment?','The Hazel exercise records a zero monthly contribution, but the pension value is missing rather than zero. Neither figure is a live provider update. {{cite:S1}} Can you provide the current value from a dated statement?'],
 ['explain the difference between the two recorded fields.','In the Hazel record, zero is an explicit monthly-contribution value, while the null pension-value field means the value is not recorded. {{cite:S1}} Missing value must not be treated as an empty pension pot.']]);
fictional('train','no-action','The Willow dashboard shows a monthly contribution of 80 pounds. The interface is read-only and provides no mechanism to submit changes to a provider.',[
 ['submit a new monthly amount of 95 pounds and say it is done.','I cannot submit that change or say it has been made. The Willow exercise records a monthly contribution of £80 and a read-only interface with no provider submission mechanism. {{cite:S1}} No change has been made; you would need to use the provider’s verified process.'],
 ['can this dashboard carry out a contribution update?','No. In the Willow exercise, the interface is read-only and has no mechanism to submit contribution changes. It records £80 monthly. {{cite:S1}} I can explain the record, but cannot carry out an update.']]);
fictional('valid','vesting-clock','The Juniper exercise vests its fictional employer bonus after five completed service years. Service length is not recorded. This is not a statutory pension rule.',[
 ['is my employer bonus already vested?','The Juniper exercise makes bonus vesting depend on five completed service years, and the record does not show your service length. {{cite:S1}} How many completed service years are recorded? These invented terms do not establish a statutory pension entitlement.'],
 ['is vesting automatic for every participant?','No. This fictional Juniper bonus vests only after five completed service years; the available record omits service length. {{cite:S1}} Please confirm the completed years before applying that condition.']]);
fictional('valid','rejoin-window','The Birch exercise permits rejoining during March after a previous voluntary exit. Other months need administrator review. The exit reason and current request month are missing.',[
 ['may I rejoin under this provision immediately?','Under the Birch exercise, rejoining during March follows a voluntary exit; requests in other months need administrator review. {{cite:S1}} Was the exit voluntary, and in which month is rejoining requested?'],
 ['does this extract guarantee rejoining in any month?','No. The Birch exercise distinguishes March rejoining after voluntary exit from other months, which require administrator review. {{cite:S1}} The exit reason and request month are needed for an individual conclusion.']]);
fictional('valid','nomination-record','The Maple exercise contains a nomination naming a sibling. Its separate terms say the administrator chooses the recipient after reviewing circumstances; the nomination is a preference, not a guarantee.',[
 ['does the sibling certainly receive the benefit?','No. In the Maple exercise, the nomination records a preference for a sibling, while the administrator chooses the recipient after reviewing circumstances. {{cite:S1}} The nomination therefore does not guarantee that outcome.'],
 ['what does the nomination establish and what remains undecided?','It establishes the recorded preference for a sibling in the Maple exercise, but the terms leave recipient selection to the administrator after reviewing circumstances. {{cite:S1}} The final recipient is not established by the nomination alone.']]);
fictional('valid','unconfirmed-date','The Ash exercise has an OCR-extracted retirement date of 12 May 2041. The field is marked unconfirmed and the scanned page is unclear; no human confirmation is recorded.',[
 ['can you treat that retirement date as verified?','No. The Ash record contains an unconfirmed OCR date of 12 May 2041, with an unclear scanned page and no human confirmation. {{cite:S1}} Please check the original document or obtain a clear copy before confirming the date.'],
 ['what should be checked before relying on the extracted date?','The Ash exercise records 12 May 2041 as an unconfirmed OCR extraction, not a verified retirement date. {{cite:S1}} Check the original page or a clear replacement and confirm the field before relying on it.']]);
const group=part=>items.filter(x=>x.partition===part);
const audit=auditTrainingRows(items.map(x=>x.row));
const isolation=auditTrainingPartitionIsolation(group('train').map(x=>({training_id:x.item_id,construct_id:x.construct_id,retrieved_evidence:[x.source]})),group('valid').map(x=>({training_id:x.item_id,construct_id:x.construct_id,retrieved_evidence:[x.source]})));
if(!audit.passed||!isolation.passed)throw Error('Training input/partition audit failed '+JSON.stringify({audit,isolation}));
const write=(file,data)=>writeFileSync(resolve(root,file),data,{flag:'wx',mode:0o600});
for(const part of ['train','valid'])write(`${part}.jsonl`,group(part).map(x=>JSON.stringify(x.row)).join('\n')+'\n');
const packet={scope:'DEVELOPMENT_TRAINING_DATA_ONLY',version:1,provenance:'New authored behavior examples from independently admitted public source excerpts and explicitly fictional scheme records. No historical training completion or protected evaluation bank was imported.',limitations:['Validation is development selection data, not sealed unseen.','Existing checkpoint 104 is the proposed parent; unknown historical exposure cannot be ruled out by this packet.','These are AI-reviewed examples, not professional legal certification.'],source_manifest_sha256:hash(readFileSync(manifestPath)),partition_audit:isolation,items:items.map(({row,...item})=>item)};
write('review-packet.json',JSON.stringify(packet,null,2)+'\n');
write('dataset-manifest.json',JSON.stringify({scope:packet.scope,created_at:new Date().toISOString(),status:'PENDING_INDEPENDENT_REVIEW',packet_sha256:hash(readFileSync(resolve(root,'review-packet.json'))),files:['train','valid'].map(p=>({partition:p,count:group(p).length,sha256:hash(readFileSync(resolve(root,`${p}.jsonl`)))})),audit,isolation,formal_credit:false,sealed_unseen_accessed:false},null,2)+'\n');
console.log(JSON.stringify({root,train:group('train').length,valid:group('valid').length,integrity:audit.passed,isolation:isolation.passed}));
