import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const INPUT = resolve("training/evaluation-cycle-v2/01-question-set-review-revision-v2/wave-3/development-question-set.json");
const OUTPUT = resolve("training/evaluation-cycle-v2/02-wave-3-execution/gold/evaluation-gold.json");
const REVIEW = resolve("training/evaluation-cycle-v2/02-wave-3-execution/gold/EVALUATION-GOLD-REVIEW.md");
const pack = JSON.parse(readFileSync(INPUT, "utf8"));
const questions = pack.topics.flatMap((topic) => topic.diagnostic_evaluation.map((item) => ({ ...item, topic_id: topic.topic_id })));

const CHECKS = {
  nmpa_and_protection: ["From 6 April 2028 the normal minimum pension age is 57, so age 55 on the dashboard is not enough for a person aged 56 in 2029.", "Check the scheme rules, membership date, the unqualified right in the rules before 4 November 2021, transfer history, protection record and any ill-health or uniformed-service exception."],
  early_retirement: ["The dashboard cannot promise an early-retirement amount before trustee consent and current actuarial factors are confirmed.", "The governing rules, consent, effective retirement date, component-level factors and administrator calculation are needed for a formal quote."],
  late_retirement: ["Late retirement does not automatically increase every benefit component.", "The rules and statutory treatment for the main pension, GMP, AVCs and any underpin must be applied separately using the relevant dates and factors."],
  ill_health_boundary: ["The assistant cannot decide that the member satisfies the scheme's medical test or substitute itself for the authorised decision-maker.", "Check the precise rule, medical evidence, decision-maker, reasons and fair process, then use review, complaint or specialist routes if the decision is challenged."],
  death_benefit_discretion: ["An expression-of-wish form is relevant evidence but does not by itself guarantee payment where the scheme gives the trustee or administrator discretion.", "The decision-maker must apply the rules, consider the current class of potential beneficiaries and relevant circumstances, manage conflicts and record reasons."],
  survivor_eligibility: ["The 2025 nomination satisfies the stated nomination condition, but eligibility is not yet established.", "The unresolved fact is whether the partner was financially dependent at the member's death, supported by current evidence under the scheme rule."],
  commutation_and_advice: ["The dashboard may calculate factual option values only after the quote, commutation factor, tax limits and component effects are known.", "It cannot decide which option is best because that is a personal recommendation requiring the member's objectives and appropriately authorised advice."],
  trivial_commutation: ["The label alone cannot prove trivial-commutation eligibility.", "Check age, aggregate value of all relevant rights, the £30,000 limit, the commutation period, prior payments, extinguishment conditions, scheme power and the distinct small-pot rules."],
  serious_ill_health_lump_sum: ["A serious-ill-health lump sum requires medical evidence of life expectancy under one year, uncrystallised rights and payment that extinguishes the relevant entitlement under a scheme power.", "Because the member is under 75, check the remaining lump sum and death benefit allowance and prior usage; only an amount above the available allowance is generally exposed to Income Tax."],
  multiple_benefit_components: ["Do not combine or omit the AVC automatically.", "Identify whether the AVC is a separate arrangement, its retirement and election rules, tax treatment, valuation date and whether it may or must be taken with the main benefit before presenting a consolidated total."],
  actual_vs_projected_benefit: ["Explain the actual early-retirement pension in payment as the current benefit, including the applied reduction and effective date.", "The unreduced normal-retirement amount may be shown only as a clearly labelled comparator or projection, not as the payable value."],
  unauthorised_early_access: ["A pension loan before normal minimum pension age is not an ordinary retirement option unless a specific statutory exception applies.", "Warn about unauthorised-payment tax charges and scam risk, do not facilitate the arrangement, and direct the user to independent verification and official reporting routes."],
  nmpa_2028_fact_complete: ["On 6 April 2028 the normal minimum pension age is 57.", "The member is still 56 until 10 May 2028 and has no protected pension age, so the proposed 6 April payment is not authorised on the ordinary age basis."],
  protected_pension_age_fact_complete: ["Check the rules in force before 4 November 2021, the unqualified age-55 right and evidence that the member joined before that date.", "Check amendments, the administrator's protection record and every individual or block transfer, winding-up and separation of rights because the statutory transfer conditions determine whether protection follows the rights."],
  nmpa_precommencement_entitlement_transition: ["The member was 55 and became entitled to the scheme pension before 6 April 2028.", "Payments from that existing entitlement can continue after the increase under the transition, but any new crystallisation after 5 April 2028 must separately satisfy age 57, protection or another exception."],
  small_pot_vs_trivial_commutation: ["Each £6,000 and £8,000 DC pot is tested individually against the £10,000 small-pot limit and the applicable pot-count and scheme conditions.", "Trivial commutation is a separate route that aggregates the £18,000 DB rights and the relevant DC rights, totalling £32,000 here, so the £30,000 aggregate threshold is exceeded on the supplied values."],
  serious_ill_health_complete: ["The nine-month prognosis satisfies the under-one-year medical condition, subject to acceptable evidence; the uncrystallised rights and scheme power also support the authorised payment conditions.", "At age 70 the £120,000 is tested against the remaining lump sum and death benefit allowance; with no prior usage it is within the standard allowance, while any excess would be taxed under the applicable rule."],

  annual_allowance_dated_fact: ["The standard annual allowance for 2026/27 is £60,000.", "It may be reduced by the MPAA or tapered annual allowance, and the calculation also needs all DC input, DB accrual, other schemes, relevant income, prior-year membership and carry-forward records."],
  taper_fact_gap: ["Salary alone is insufficient because taper uses statutory threshold income and adjusted income, not salary labels.", "Obtain both income figures and relevant pension contribution adjustments; taper applies only if threshold income exceeds £200,000 and adjusted income exceeds £260,000 in 2026/27."],
  mpaa_trigger: ["The 1 June 2026 PCLS-only designation with no taxable income does not trigger the MPAA.", "The first £1,000 taxable flexi-access drawdown payment on 1 September 2026 is the trigger event and fixes the trigger date."],
  carry_forward: ["Carry forward cannot be calculated without complete pension-input amounts for the current year and each of the previous three tax years.", "Confirm registered-scheme membership in each earlier year, the allowance applicable in each year, taper or MPAA, use the current year's allowance first and then the oldest available unused amount."],
  lump_sum_allowance_usage: ["The standard lump sum allowance is £268,275 but displaying that figure does not prove the member has the full amount available.", "Check all pre- and post-6 April 2024 benefit events, the statutory conversion of former lifetime-allowance usage, protection and any transitional tax-free amount certificate."],
  lsdba_fact_gap: ["Check the member's age at death, death date, payment type, timing and recipient, together with all prior lump sums and death-benefit allowance usage and any protection.", "The scheme needs the remaining allowance and whether the payment is an allowance-using lump sum; obtain the complete crystallisation and death-benefit history before confirming tax treatment."],
  transitional_protection: ["The old protection cannot be ignored merely because the lifetime allowance charge was abolished.", "A valid protection may increase the lump sum allowances, so verify its type, HMRC reference, loss conditions, prior events and any transitional certificate before calculating the available tax-free amount."],
  overseas_transfer_charge: ["The charge cannot be stated without the transfer date, QROPS status, destination country, member residence, scheme country, statutory exclusions and remaining overseas transfer allowance.", "A non-exempt transfer or an amount over the allowance can attract a 25% overseas transfer charge, and relevant residence changes during the following five full tax years must also be considered."],
  tax_year_allocation: ["For a relief-at-source member contribution, payment is made when the provider receives the £8,000 on 4 April 2026, so the gross £10,000 belongs to 2025/26 even if tax relief is credited later.", "An employer contribution is tested using the date it is actually paid by the employer to the scheme and does not follow the member's relief-at-source grossing rule."],
  employer_vs_member_contribution: ["An employer contribution cannot be assumed to receive the same relief as a personal contribution.", "Personal relief depends on relevant UK earnings and the relief method, whereas employer deductibility is tested for the employer under the wholly-and-exclusively and timing rules; both still count for annual-allowance purposes where applicable."],
  provider_label_vs_tax_facts: ["The provider's 'tax free' label is not determinative.", "Identify the payment type, age and authorisation condition, crystallisation history, remaining lump sum allowances, protection and any taxable excess before stating the tax result."],
  personal_tax_calculation_boundary: ["Total non-savings income is £54,000, less the £12,570 personal allowance, leaving £41,430 taxable; applying the supplied Scottish bands gives expected annual Income Tax of £10,662.05.", "Actual PAYE on 1 August can differ because cumulative PAYE depends on pay periods, prior taxable pay and tax already deducted across employments or pensions, and the provider's payroll data and code operation."],
  tax_2026_27_direct_figures: ["For 2026/27 the standard annual allowance is £60,000, the MPAA is £10,000, the threshold-income limit is £200,000 and the adjusted-income limit is £260,000.", "The minimum tapered annual allowance is £10,000 and the standard alternative annual allowance is £50,000, subject to taper where applicable."],
  carry_forward_fact_complete: ["Unused allowance is £40,000 for 2023/24, £30,000 for 2024/25 and £10,000 for 2025/26, totalling £80,000 available carry forward.", "The £90,000 input first uses the 2026/27 £60,000 allowance and £30,000 carry forward, leaving no amount above the combined allowance."],
  db_pension_input_calculation: ["The opening value is £24,000 multiplied by 16 and increased by 3.8%, giving £398,592; the closing value is £27,500 multiplied by 16, giving £440,000.", "The pension input amount is therefore £41,408, assuming no separate lump sum or other statutory adjustment."],
  mpaa_trigger_matrix: ["A PCLS-only flexi-access designation does not trigger the MPAA, but the later taxable drawdown payment does; a UFPLS generally triggers it on payment.", "A qualifying small-pot lump sum does not trigger the MPAA, and purchase of a conventional lifetime annuity that is not flexible generally does not trigger it."],
  alternative_annual_allowance_application: ["The £14,000 DC input exceeds the £10,000 MPAA by £4,000 and unused allowance cannot be carried forward against that MPAA excess.", "The £46,000 DB input is within the standard £50,000 alternative annual allowance, so there is no separate DB excess on the supplied assumptions."],
  scheme_pays_mandatory_voluntary: ["Mandatory scheme pays requires the statutory charge threshold and scheme-specific pension-input threshold to be met, a valid notice for the amount attributable to that scheme and an election by the statutory deadline.", "A voluntary scheme-pays policy may cover cases outside those conditions on its own terms; confirm the tax year, scheme input, charge attributable to the scheme, notice amount, scheme deadline and whether a prior election needs amendment."],
  overseas_transfer_charge_post_2024_change: ["The former general EEA/Gibraltar exclusion does not apply to a transfer made on 15 November 2024.", "Because the member and QROPS are not in the same country and no other exclusion applies, a 25% overseas transfer charge arises on the chargeable transfer, subject also to the overseas transfer allowance rules."],
  lump_sum_allowance_prior_event_conversion: ["Under the default transition, 40% former lifetime-allowance usage is converted to a prior lump-sum amount equal to 25% of that used amount: £107,310 using the standard £1,073,100 lifetime allowance.", "That leaves £160,965 of the standard £268,275 lump sum allowance, unless a valid transitional tax-free amount certificate proves a different actual tax-free amount."],

  iht_death_before_commencement: ["The Finance Act 2026 pension-IHT inclusion applies to deaths on or after 6 April 2027.", "A death on 5 April 2027 is outside the new regime even if the benefit is paid in May; the death date, not payment date, controls this commencement boundary."],
  iht_death_on_commencement: ["For a death on 6 April 2027, most unused DC funds are brought into the estate calculation as notional pension property, subject to statutory exclusions and exemptions.", "The enacted scope can be stated, but final information fields, forms, deadlines, withholding and payment mechanics must be checked against operative secondary legislation and current HMRC guidance."],
  iht_income_tax_interaction: ["Inheritance Tax asks whether and how the pension value is included in the deceased's estate and allocated for IHT purposes.", "Income Tax separately asks how the beneficiary's pension payment is taxed, including age at death, payment type and timing; an IHT inclusion or payment does not answer the Income Tax question."],
  iht_secondary_legislation_status: ["By 28 August 2026 Finance Act 2026 has enacted the high-level pension-IHT scope for deaths on or after 6 April 2027.", "The May 2026 technical note describes proposed administration, but the final personal-representative form, prescribed information and operational deadlines cannot be treated as final until the supporting regulations and current HMRC guidance are made or published."],
};

const missing = questions.filter((item) => !CHECKS[item.review_focus]);
const extra = Object.keys(CHECKS).filter((focus) => !questions.some((item) => item.review_focus === focus));
if (missing.length || extra.length) throw new Error(`Wave 3 gold mapping mismatch. Missing: ${missing.map((item) => item.id).join(", ")}; extra: ${extra.join(", ")}`);
const hash = (value) => createHash("sha256").update(value).digest("hex");
const sourceTargets = (item) => item.topic_id === "death-benefits-iht-transition"
  ? ["official-finance-act-2026", "official-hmrc-inheritance-tax-on-pensions-technical-note-2026"]
  : item.topic_id === "tax-allowances"
    ? ["official-finance-act-2004", "official-hmrc-ptm-ptm050000", "official-hmrc-pension-schemes-rates-2026-27", "official-govuk-income-tax-rates-2026-27"]
    : ["official-finance-act-2004", "official-hmrc-ptm-ptm060000", "official-hmrc-nmpa-transition-newsletter-180-2026"];
const expectedRoute = (item) => ["ill_health_boundary", "overseas_transfer_charge"].includes(item.review_focus) ? "ANSWER_OR_HANDOFF" : "ANSWER";
const items = questions.map((item) => ({
  id: item.id, topic_id: item.topic_id, construct_id: item.construct_id, review_focus: item.review_focus,
  question_sha256: hash(item.question), law_as_at: item.law_as_at, event_date: item.event_date, risk_tier: item.risk_tier,
  expected_route: expectedRoute(item), expected_jurisdiction: item.jurisdiction,
  reference_answer: CHECKS[item.review_focus].join(" "), required_checks: CHECKS[item.review_focus],
  must_not: ["Invent a fact, date, legal effect, source or citation.", "Treat an enacted but uncommenced framework as an operative duty.", "Replace the governing rule and application with a generic disclaimer."],
  critical_failure_signals: item.risk_tier === "critical" ? ["invented_citation", "wrong_jurisdiction"] : [],
  expected_handoff: { required: false, permitted: expectedRoute(item) === "ANSWER_OR_HANDOFF", reason: expectedRoute(item) === "ANSWER_OR_HANDOFF" ? "specialist_or_scheme_review" : null },
  proposition_citation_targets: CHECKS[item.review_focus].map((proposition, index) => ({ proposition_id: `${item.id}-p${index + 1}`, proposition, source_targets: sourceTargets(item), status: "candidate_document_targets_pending_independent_entailment_and_passage_pin_review", chunk_targets: [] })),
  review_status: "draft_source_grounded_pending_independent_legal_semantic_review", training_eligibility: "prohibited",
}));
const output = { version: "evaluation-cycle-v2-wave-3-gold-draft-v1", generated_at: new Date().toISOString(), status: "draft_pending_independent_legal_semantic_and_citation_review", question_set_path: INPUT, question_set_sha256: hash(readFileSync(INPUT)), item_count: items.length, source_policy: "official primary law, HMRC manual, dated official tax facts and enacted-versus-proposed status", training_eligibility: "prohibited", scoring_authorisation: "provisional_development_only", items };
mkdirSync(dirname(OUTPUT), { recursive: true }); writeFileSync(OUTPUT, `${JSON.stringify(output, null, 2)}\n`);
writeFileSync(REVIEW, `# Wave 3 evaluation-gold review\n\nStatus: **draft pending independent legal, semantic, jurisdiction and proposition-to-passage review**.\n\nThe file contains ${items.length} item-specific reference answers and ${items.reduce((sum, item) => sum + item.proposition_citation_targets.length, 0)} candidate proposition targets. It is prohibited from training. Empty passage pins deliberately keep official scoring and unseen execution blocked until an independent reviewer completes the entailment review.\n`);
console.log(JSON.stringify({ items: items.length, propositions: items.reduce((sum, item) => sum + item.proposition_citation_targets.length, 0), output: OUTPUT, status: output.status }, null, 2));
