import {readFileSync,writeFileSync,copyFileSync,existsSync,mkdirSync,statSync,constants} from 'node:fs';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {boundedFileDigest} from './lib/boundedFileDigest.mjs';
import {selectDurationCandidate} from './lib/adaptabilityDurationSelection.mjs';
const root=resolve(process.argv[2]||'');if(!process.argv[2])throw Error('Run root required');
const plan=JSON.parse(readFileSync(resolve(root,'training-plan.json')));
const hash=boundedFileDigest;
for(const r of plan.bound_inputs)if(hash(r.path)!==r.sha256)throw Error('Training bound input changed: '+r.path);
const log=readFileSync(resolve(root,'training-output.log'),'utf8');
const exit=JSON.parse(readFileSync(resolve(root,'training-exit.json')));if(exit.exit_code!==0||!log.includes('"event": "training_finished"'))throw Error('Clean training completion missing');
const validations=[...log.matchAll(/Iter\s+(\d+): Val loss\s+([0-9.]+)/g)].map(m=>({iteration:Number(m[1]),loss:Number(m[2])}));
const trains=[...log.matchAll(/Iter\s+(\d+): Train loss\s+([0-9.]+)/g)].map(m=>({iteration:Number(m[1]),loss:Number(m[2])}));
const peak=Math.max(0,...[...log.matchAll(/Peak mem\s+([0-9.]+)\s+GB/g)].map(m=>Number(m[1])));
if(trains.at(-1)?.iteration!==48||!peak||peak>plan.memory_limit_gb)throw Error('Incomplete training or memory ceiling exceeded');
const exact=JSON.parse(readFileSync(resolve(root,'exact-checkpoint-validation.json')));
if(exact.validation_sha256!==hash(resolve(plan.dataset,'valid.jsonl')))throw Error('Exact validation split mismatch');
if(JSON.stringify(exact.records.map(x=>x.iteration).sort((a,b)=>a-b))!==JSON.stringify([12,24,36,48]))throw Error('Exact validation must contain each candidate once');
const candidates=[12,24,36,48].map(iteration=>{const path=resolve(plan.train.adapter_path,String(iteration).padStart(7,'0')+'_adapters.safetensors');const record=exact.records.find(v=>v.iteration===iteration);const loss=record?.validation_loss;if(!existsSync(path)||!Number.isFinite(loss)||record.sha256!==hash(path))throw Error('Exact persisted checkpoint validation missing');return {iteration,validation_loss:loss,source_checkpoint:path,sha256:hash(path),size_bytes:statSync(path).size};}).sort((a,b)=>a.validation_loss-b.validation_loss||a.iteration-b.iteration);
const baseline=exact.training_validation_events.find(v=>v.iteration===0)?.val_loss;
if(!Number.isFinite(baseline))throw Error('Parent baseline validation is missing');
const updateAccounting=JSON.parse(readFileSync(resolve(root,'optimizer-update-accounting.json')));
if(updateAccounting.completed_optimizer_updates!==48||updateAccounting.microbatches!==48||updateAccounting.all_final_trainable_parameters_finite!==true||updateAccounting.changed_trainable_tensors<1)throw Error('Exact optimiser-update and finite parameter-delta proof missing');
const semanticReview=JSON.parse(readFileSync(resolve(root,'checkpoint-semantic-review.json')));
if(semanticReview.validation_sha256!==exact.validation_sha256)throw Error('Semantic review validation identity mismatch');
const expectedUpdates=[0,12,24,36,48];
if(JSON.stringify(semanticReview.records.map((item)=>item.additional_update_count).sort((a,b)=>a-b))!==JSON.stringify(expectedUpdates))throw Error('Semantic review must assess baseline and every scheduled checkpoint exactly once');
const assessed=semanticReview.records.map((reviewRecord)=>{
 const metric=reviewRecord.additional_update_count===0?{validation_loss:baseline}:{validation_loss:candidates.find((item)=>item.iteration===reviewRecord.additional_update_count)?.validation_loss};
 return {...reviewRecord,...metric};
});
const decision=selectDurationCandidate(assessed);
if(!decision.selected)throw Error(`No duration candidate may be selected: ${decision.reason}`);
const selectedUpdate=decision.selected.additional_update_count;
const best=selectedUpdate===0?null:candidates.find((item)=>item.iteration===selectedUpdate);
const selected=best?resolve(root,'selected-adapter'):null;
if(selected){if(existsSync(selected))throw Error('Refusing existing selection');mkdirSync(selected);copyFileSync(best.source_checkpoint,resolve(selected,'adapters.safetensors'),constants.COPYFILE_EXCL);copyFileSync(resolve(plan.train.adapter_path,'adapter_config.json'),resolve(selected,'adapter_config.json'),constants.COPYFILE_EXCL);}
const write=(name,value)=>writeFileSync(resolve(root,name),JSON.stringify(value,null,2)+'\n',{flag:'wx',mode:0o600});
write('training-run-manifest.json',{version:'adaptability-duration-study-run-v3',status:'completed_development_evaluation_pending',completed_at:new Date().toISOString(),base_model:{path:plan.base_path,model_sha256:plan.base_sha256},parent:{checkpoint:104,adapter_sha256:plan.bound_inputs.find(x=>x.path===plan.parent_adapter).sha256},plan_sha256:hash(resolve(root,'training-plan.json')),output_sha256:hash(resolve(root,'training-output.log')),hyperparameters:plan.hyperparameters,update_accounting:updateAccounting,metrics:{validation_loss:validations,train_loss:trains,peak_memory_gb:peak,baseline_validation_loss:baseline,selected_validation_loss:decision.selected.validation_loss},review:plan.review,semantic_review:semanticReview,formal_credit:false,sealed_unseen_accessed:false});
write('checkpoint-selection.json',{version:'adaptability-checkpoint-selection-v3',model_version:best?'pension-assistant-adaptability-duration-study-v3':'pension-assistant-cumulative-t4-legal-v1-selected',selected_additional_update_count:selectedUpdate,selected_validation_loss:decision.selected.validation_loss,selected_adapter_path:selected,source_checkpoint:best?.source_checkpoint || plan.parent_adapter,adapter_sha256:best?.sha256 || plan.bound_inputs.find(x=>x.path===plan.parent_adapter).sha256,adapter_config_sha256:selected?hash(resolve(selected,'adapter_config.json')):plan.bound_inputs.find(x=>x.path.endsWith('adapter_config.json'))?.sha256,policy:plan.selection_policy,decision_reason:decision.reason,parent_checkpoint:104,candidates:assessed,development_only:true});
console.log(JSON.stringify({selected_additional_update_count:selectedUpdate,baseline_validation_loss:baseline,selected_validation_loss:decision.selected.validation_loss,adapter_sha256:best?.sha256 || plan.bound_inputs.find(x=>x.path===plan.parent_adapter).sha256,peak_memory_gb:peak,qualified:false}));
