import {readFileSync,writeFileSync,mkdirSync,copyFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {boundedFileDigest as hash} from './lib/boundedFileDigest.mjs';
const [sourceArg,rootArg]=process.argv.slice(2);if(!sourceArg||!rootArg)throw Error('Interrupted recovery root and fresh assessment root required');
const source=resolve(sourceArg),root=resolve(rootArg);if(existsSync(root))throw Error('Refusing existing partial assessment');
const plan=JSON.parse(readFileSync(resolve(source,'training-plan.json')));
for(const x of plan.bound_inputs)if(hash(x.path)!==x.sha256)throw Error('Source binding changed: '+x.path);
const exitPath=resolve(source,'recovery-exit.json'),exit=JSON.parse(readFileSync(exitPath));
if(exit.aborted!=='SWAP_GROWTH_LIMIT')throw Error('Not the declared interrupted recovery');
const reconstruction=JSON.parse(readFileSync(resolve(source,'reconstruction-receipt.json')));
const candidate=resolve(source,'reconstructed-parent/adapters.safetensors');
if(hash(candidate)!==reconstruction.full_sha256||!reconstruction.frozen_parent_tensors_unchanged)throw Error('Step12 candidate identity mismatch');
plan.partial_assessment={scope:'PARTIAL_INTERRUPTED_STUDY_NO_NEW_TRAINING',interrupted_exit:exitPath,source_root:source,candidate_lineage_updates:[0,12],excluded_unscheduled_recovery_lineage:19,full_study_complete:false};
for(const path of [exitPath,candidate,resolve(source,'reconstruction-receipt.json')])plan.bound_inputs.push({path,sha256:hash(path)});
mkdirSync(root,{mode:0o700});mkdirSync(resolve(root,'reconstructed-parent'));
for(const file of ['adapters.safetensors','adapter_config.json'])copyFileSync(resolve(source,'reconstructed-parent',file),resolve(root,'reconstructed-parent',file));
copyFileSync(resolve(source,'training.sb'),resolve(root,'training.sb'));
writeFileSync(resolve(root,'training-plan.json'),JSON.stringify(plan,null,2),{flag:'wx',mode:0o600});
const paths=[resolve(root,'training-plan.json'),resolve('scripts/preparePartialAdaptabilityAssessment.mjs'),resolve('scripts/runAdaptabilitySelection.mjs'),resolve('ml/evaluate_adaptability_checkpoints.py'),resolve('scripts/finalizePartialAdaptabilityAssessment.mjs'),resolve('scripts/lib/adaptabilityDurationSelection.mjs'),resolve('scripts/lib/adaptabilitySelectionControls.mjs'),resolve('scripts/lib/qualification-worker/aiReview.mjs'),resolve('config/qualification-worker.json')];
writeFileSync(resolve(root,'selection-binding.json'),JSON.stringify({scope:plan.partial_assessment.scope,maximum_generations:16,maximum_reviewer_calls:4,maximum_tokens_per_generation:192,maximum_model_seconds:7200,automatic_retries:0,bound_inputs:paths.map(path=>({path,sha256:hash(path)}))},null,2),{flag:'wx',mode:0o600});
console.log(JSON.stringify({root,training_started:false,partial_only:true}));
